<a href="https://colab.research.google.com/github/MajidAlmheiri/AI-Agent-Dev-Assesment-Email-Agent/blob/main/Lab9A_Multi_Class.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Uploading files to google colab

In [2]:
from google.colab import files
uploaded = files.upload()

Saving Dry_Bean_Dataset_multiclass.csv to Dry_Bean_Dataset_multiclass.csv

# Dataset cleaning and information

In [8]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

# Read Dry Bean csv file
df = pd.read_csv("Dry_Bean_Dataset_multiclass.csv")

# Displaying the dataset
display(df.head())
print()

# Displaying dataset description
print("Dataset description: \n")
display(df.describe())
print()

# Finding the missing values and dropping them
print("Shape before dropping missing values: ", df.shape)
print("Columns with missing values: ")
display(df.isnull().sum())
print()
df.dropna(inplace = True)
print("Columns after dropping missing values: ")
display(df.isnull().sum())
print("Shape after dropping missing values: ", df.shape)
print()

# Checking how many classes exist
print("Number of unique classes: ", sep = '')
display(df["Class"].unique())
print()

# Checking how many classes exist
print("Class distribution: ")
display(df["Class"].value_counts())
print()

# Since the machines don't understand strings, we will use the encoder to give each class an integer label. Sort of like a key in a dict
# Creating label encoder object
le = LabelEncoder()

# The fit_transform function is used to learn and assign numbers to the unique values of an array (in this cases its the output class)
df["Class"] = le.fit_transform(df["Class"])

# Checking the new class numbering
display(df["Class"].unique())

,Area,Perimeter,MajorAxisLength,MinorAxisLength,AspectRation,Eccentricity,ConvexArea,EquivDiameter,Extent,Solidity,roundness,Compactness,ShapeFactor1,ShapeFactor2,ShapeFactor3,ShapeFactor4,Class
0,28395,610.291,208.178117,173.888747,1.197191,0.549812,28715,190.141097,0.763923,0.988856,0.958027,0.913358,0.007332,0.003147,0.834222,0.998724,SEKER
1,28734,638.018,200.524796,182.734419,1.097356,0.411785,29172,191.272751,0.783968,0.984986,0.887034,0.953861,0.006979,0.003564,0.909851,0.998430,SEKER
2,29380,624.110,212.826130,175.931143,1.209713,0.562727,29690,193.410904,0.778113,0.989559,0.947849,0.908774,0.007244,0.003048,0.825871,0.999066,SEKER
3,30008,645.884,210.557999,182.516516,1.153638,0.498616,30724,195.467062,0.782681,0.976696,0.903936,0.928329,0.007017,0.003215,0.861794,0.994199,SEKER
4,30140,620.134,201.847882,190.279279,1.060798,0.333680,30417,195.896503,0.773098,0.990893,0.984877,0.970516,0.006697,0.003665,0.941900,0.999166,SEKER

Dataset description:

,Area,Perimeter,MajorAxisLength,MinorAxisLength,AspectRation,Eccentricity,ConvexArea,EquivDiameter,Extent,Solidity,roundness,Compactness,ShapeFactor1,ShapeFactor2,ShapeFactor3,ShapeFactor4
count,13611.000000,13611.000000,13611.000000,13611.000000,13611.000000,13611.000000,13611.000000,13611.000000,13611.000000,13611.000000,13611.000000,13611.000000,13611.000000,13611.000000,13611.000000,13611.000000
mean,53048.284549,855.283459,320.141867,202.270714,1.583242,0.750895,53768.200206,253.064220,0.749733,0.987143,0.873282,0.799864,0.006564,0.001716,0.643590,0.995063
std,29324.095717,214.289696,85.694186,44.970091,0.246678,0.092002,29774.915817,59.177120,0.049086,0.004660,0.059520,0.061713,0.001128,0.000596,0.098996,0.004366
min,20420.000000,524.736000,183.601165,122.512653,1.024868,0.218951,20684.000000,161.243764,0.555315,0.919246,0.489618,0.640577,0.002778,0.000564,0.410339,0.947687
25%,36328.000000,703.523500,253.303633,175.848170,1.432307,0.715928,36714.500000,215.068003,0.718634,0.985670,0.832096,0.762469,0.005900,0.001154,0.581359,0.993703
50%,44652.000000,794.941000,296.883367,192.431733,1.551124,0.764441,45178.000000,238.438026,0.759859,0.988283,0.883157,0.801277,0.006645,0.001694,0.642044,0.996386
75%,61332.000000,977.213000,376.495012,217.031741,1.707109,0.810466,62294.000000,279.446467,0.786851,0.990013,0.916869,0.834270,0.007271,0.002170,0.696006,0.997883
max,254616.000000,1985.370000,738.860154,460.198497,2.430306,0.911423,263261.000000,569.374358,0.866195,0.994677,0.990685,0.987303,0.010451,0.003665,0.974767,0.999733

Shape before dropping missing values:  (13611, 17)
Columns with missing values:

Area               0
Perimeter          0
MajorAxisLength    0
MinorAxisLength    0
AspectRation       0
Eccentricity       0
ConvexArea         0
EquivDiameter      0
Extent             0
Solidity           0
roundness          0
Compactness        0
ShapeFactor1       0
ShapeFactor2       0
ShapeFactor3       0
ShapeFactor4       0
Class              0
dtype: int64

Columns after dropping missing values:

Area               0
Perimeter          0
MajorAxisLength    0
MinorAxisLength    0
AspectRation       0
Eccentricity       0
ConvexArea         0
EquivDiameter      0
Extent             0
Solidity           0
roundness          0
Compactness        0
ShapeFactor1       0
ShapeFactor2       0
ShapeFactor3       0
ShapeFactor4       0
Class              0
dtype: int64

Shape after dropping missing values:  (13611, 17)

Number of unique classes:

array(['SEKER', 'BARBUNYA', 'BOMBAY', 'CALI', 'HOROZ', 'SIRA', 'DERMASON'],
      dtype=object)

Class distribution:

Class
DERMASON    3546
SIRA        2636
SEKER       2027
HOROZ       1928
CALI        1630
BARBUNYA    1322
BOMBAY       522
Name: count, dtype: int64

array([5, 0, 1, 2, 4, 6, 3])

# Dataset splitting and training

In [13]:
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier

# Assigning inputs and outputs
x = df.loc[:, df.columns != "Class"]
y = df.loc[:, df.columns == "Class"]

# Training and testing split using 80/20
x_train, x_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size = 0.2,
    train_size = 0.8,
    random_state = 2,
    )

# Creating MLP model and specifying its parameters
model = MLPClassifier(
    solver = "adam",
    alpha = 0.001,
    hidden_layer_sizes = (5),
    activation = "logistic",
    max_iter = 100,
    tol = 0.0001
    )

# Now we will train our model
model.fit(x_train, y_train)

# Now we will test the model
y_pred = model.predict(x_test)

/usr/local/lib/python3.13/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:1124: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

# Results and metrics

In [14]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report

# Confusion matrix
print("Confusion matrix: \n")
print(confusion_matrix(y_test, y_pred))
print()
print("Classification report: \n")
print(classification_report(y_test, y_pred))
print("Accuracy: ", accuracy_score(y_test, y_pred))
print("Precision: ", precision_score(y_test, y_pred, average = "weighted"))
print("Recall: ", recall_score(y_test, y_pred, average = "weighted"))
print("F1 Score: ", f1_score(y_test, y_pred, average = "weighted"))

Confusion matrix:

[[  0   0   0 288   0   0   0]
 [  0   0   0 106   0   0   0]
 [  0   0   0 308   0   0   0]
 [  0   0   0 685   0   0   0]
 [  0   0   0 380   0   0   0]
 [  0   0   0 412   0   0   0]
 [  0   0   0 544   0   0   0]]

Classification report:

              precision    recall  f1-score   support

           0       0.00      0.00      0.00       288
           1       0.00      0.00      0.00       106
           2       0.00      0.00      0.00       308
           3       0.25      1.00      0.40       685
           4       0.00      0.00      0.00       380
           5       0.00      0.00      0.00       412
           6       0.00      0.00      0.00       544

    accuracy                           0.25      2723
   macro avg       0.04      0.14      0.06      2723
weighted avg       0.06      0.25      0.10      2723

Accuracy:  0.25156077855306647
Precision:  0.06328282530622495
Recall:  0.25156077855306647
F1 Score:  0.10112625194181368

/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))